name: Bug report
description: Report a bug
title: "[Bug] "
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: Describe the what's wrong. Provide as much details as possible.
    
  - type: input
    id: godot-version
    attributes:
      label: Godot version
      description: The version of Godot you're running
      placeholder: ex. v4.4.1.stable.arch_linux

  - type: checkboxes
    id: checks
    attributes:
      options:
        - label: I searched for other issues describing this bug
          required: true
        - label: The bug isn't listed in the TODO list and the feature it's referring to is implemented
          required: true
